#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin_GoogleAuth.Droid.Resource", IsApplication=true)]

namespace Xamarin_GoogleAuth.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::Xamarin_GoogleAuth.Droid.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::Xamarin_GoogleAuth.Droid.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::Xamarin_GoogleAuth.Droid.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.webview = global::Xamarin_GoogleAuth.Droid.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::Xamarin_GoogleAuth.Droid.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::Xamarin_GoogleAuth.Droid.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int slide_in_right = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int slide_out_left = 2130771969;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int fork = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int forks = 2130837505;
			
			// aapt resource value: 0x7F020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7F020002
			public const int ic_arrow_back = 2130837506;
			
			// aapt resource value: 0x7F020004
			public const int painting = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int readBook = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int running = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int workOut = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030007
			public const int date_EditText = 2130903047;
			
			// aapt resource value: 0x7F030000
			public const int Event1 = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Event2 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Event3 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Event4 = 2130903043;
			
			// aapt resource value: 0x7F030008
			public const int getCalendarsButton = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int getEventsListButton = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int getPhotosButton = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int googleLoginButton = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int imageView2 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int imageView3 = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int imageView4 = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int imageView5 = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int imageView6 = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int linearLayout1 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int textView3 = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int textView4 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int textView5 = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int textView6 = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int textView7 = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int textView8 = 2130903063;
			
			// aapt resource value: 0x7F030004
			public const int TimeEvent = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int TodoEvent1 = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int TodoEvent2 = 2130903046;
			
			// aapt resource value: 0x7F030018
			public const int webview = 2130903064;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_webview = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int googleLogin = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int title_activity_webview = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
